---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddi
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ddi-scaleway-secret
      containers:
        - name: ddi
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "800m"
              memory: "1.8Gi"
            requests:
              cpu: "500m"
              memory: "1.6Gi"
