---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddi
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ddi-scaleway-secret
      containers:
        - name: ddi
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "3"
              memory: "3.5Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
