---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ddi
  labels:
    app: ddi
spec:
  ingressClassName: "nginx"
  rules:
    - host: example.com  # Placeholder that will be replaced in overlays
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ddi
                port:
                  name: http
