---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ddi-deployment.yaml
  - ddi-service.yaml
  - ddi-ingress.yaml

configMapGenerator:
  - name: ddi-config
    literals:

images:
  - name: ddi
