---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ddi
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
